name: Deploy Dashboard

on:
  push:
    branches: [main]

jobs:
  deploy-frontend:
    name: Build and deploy frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build React app
        run: |
          cd frontend
          echo "VITE_API_URL=https://d2x3aixiot3ob4.cloudfront.net" > .env
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Upload to S3
        run: |
          aws s3 sync frontend/dist/ s3://dashboard-cicd-frontend --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3KYCWLTLQJKYG \
            --paths "/*"

  deploy-backend:
    name: Deploy backend to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids i-0174c5ab1d5f8dad4 \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["cd /home/ubuntu/dashboard-cicd && git pull origin main && cd backend && npm install && pm2 restart dashboard-api"]' \
            --region eu-west-3
