name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  deploy-backend:
    name: Deploy backend to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids i-0174c5ab1d5f8dad4 \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["cd /home/ubuntu/dashboard-cicd && git pull origin main && cd backend && npm install && pm2 restart dashboard-api"]' \
            --region eu-west-3